name = "calendar-events"
workers_dev = true
main = "build/worker/shim.mjs"
compatibility_date = "2025-06-10"

[build]
command = "worker-build --release"

[placement]
mode = "smart"

[observability]
enabled = true

[[rules]]
globs = ["**/*.wasm"]
type = "CompiledWasm"
fallthrough = false

# Cron Triggers
# Docs: https://developers.cloudflare.com/workers/platform/triggers/cron-triggers/
# Configuration: https://developers.cloudflare.com/workers/wrangler/configuration/#triggers
# Test url: http://localhost:*/__scheduled?cron=*+*+*+*+*
[triggers]
crons = ["0 * * * *"]

[env.local.vars]
ENDPOINT = "http://localhost:8080"
