name = "calendar-events"
workers_dev = true
main = "build/worker/shim.mjs"
compatibility_date = "2024-03-14"

[build]
command = "worker-build --release"

[[rules]]
globs = ["**/*.wasm"]
type = "CompiledWasm"
fallthrough = false

# Cron Triggers
# Docs: https://developers.cloudflare.com/workers/platform/triggers/cron-triggers/
# Configuration: https://developers.cloudflare.com/workers/wrangler/configuration/#triggers
[triggers]
crons = ["0 22 * * *"]

[env.local.vars]
GOOGLE_APIKEY = "FILL THAT"
GOOGLE_CALENDAR_ID = "FILL THAT"
ENDPOINT = "http://localhost:8080"
